"""Single-overflight case studies using the current dt_sim policies.

Break-even and two-anchor lookahead boxes are generated by the same simulator
path used by the numbered experiments, then saved as separate panels for LaTeX
subfigures.
"""

from __future__ import annotations

import argparse
import datetime
from dataclasses import replace
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import cartopy.crs as ccrs
import matplotlib.pyplot as plt
import numpy as np
import scienceplots  # noqa: F401

from dt_sim.access import Access, Request
from dt_sim.cameras import (
    create_box,
    get_intrinsics_from_fov,
    unproject_from_orbit,
)
from dt_sim.config import SimConfig
from dt_sim.constants import Constants
from dt_sim.orbits import (
    circular_orbit,
    earth_line_intersection,
    ecef2latlong,
    eci2ecef,
    kepler2eci,
    kepler2latlong,
    propagate_orbit,
    split_orbit_track,
)
from dt_sim.scenario import build_scenario
from dt_sim.scheduling import load_worldcities
from dt_sim.simulator import _evaluate_variant

STYLE_PATH = Path(__file__).resolve().parent.parent.parent / "shreeyam.mplstyle"
plt.style.use(["science", str(STYLE_PATH)])

# ---- Default orbit / scenario: Morocco to Australia ----
H_KM = 400.0
INC_DEG = 51.6
T0 = datetime.datetime(2025, 1, 1, 8, 30, 0)
T_END = T0 + datetime.timedelta(minutes=42)
RAAN = 3.143
MEAN_ANOM = 0.770
CASE_NAME = "morocco_australia"
CASE_TAG = "paper1_04_morocco_australia"

# ---- Lookahead configuration: paper baseline ----
FIELD_OF_REGARD_DEG = 45.0
FOV_DEG = 45.0
T_SLEW_FOR_S = 25.0
PITCH_CANDIDATES = 64
N_CITIES = 10000
CLOUD_PROB = 0.66
WIDTH = 800
HEIGHT = 800

POLICIES = ("break_even", "two_anchor")
POLICY_LABELS = {
    "break_even": "break-even",
    "two_anchor": "two-anchor",
}
POLICY_COLORS = {
    "break_even": "#00c5b3",
    "two_anchor": "#4a5de9",
}
OUTPUT_STEMS = {
    "break_even": "lookahead_chain_ma_break_even",
    "two_anchor": "lookahead_chain_ma_two_anchor",
}
REQUEST_COLOR = "0.86"
UNOBSERVED_ACCESS_COLOR = "0.42"
OBSERVED_ACCESS_COLOR = "#f46009"
ORBIT_COLOR = "0.08"


def _phase_mean_anomaly(epoch: datetime.datetime, mean_anom: float,
                        t0: datetime.datetime) -> float:
    n = np.sqrt(Constants.mu / (Constants.R_E + H_KM) ** 3)
    return float((mean_anom + n * (t0 - epoch).total_seconds()) % (2 * np.pi))


_SA_EPOCH = datetime.datetime(2025, 1, 1, 0, 0, 0)
_BRAZIL_T0 = datetime.datetime(2025, 1, 1, 19, 20, 0)

CASE_CONFIGS = {
    "morocco_australia": {
        "t0": datetime.datetime(2025, 1, 1, 8, 30, 0),
        "duration_min": 42,
        "raan": 3.143,
        "mean_anom": 0.770,
        "tag": "paper1_04_morocco_australia",
        "virtual_anchor_min": None,
        "stems": {
            "break_even": "lookahead_chain_ma_break_even",
            "two_anchor": "lookahead_chain_ma_two_anchor",
        },
    },
    "brazil": {
        "t0": _BRAZIL_T0,
        "duration_min": 30,
        "raan": 0.0,
        "mean_anom": _phase_mean_anomaly(_SA_EPOCH, np.pi / 2, _BRAZIL_T0),
        "tag": "paper1_04_brazil",
        "virtual_anchor_min": 2.0,
        "stems": {
            "break_even": "lookahead_chain_brazil_break_even",
            "two_anchor": "lookahead_chain_brazil_two_anchor",
        },
    },
}


def apply_case(case_name: str) -> None:
    global T0, T_END, RAAN, MEAN_ANOM, CASE_NAME, CASE_TAG, OUTPUT_STEMS
    case = CASE_CONFIGS[case_name]
    T0 = case["t0"]
    T_END = T0 + datetime.timedelta(minutes=case["duration_min"])
    RAAN = case["raan"]
    MEAN_ANOM = case["mean_anom"]
    CASE_NAME = case_name
    CASE_TAG = case["tag"]
    OUTPUT_STEMS = case["stems"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", choices=sorted(CASE_CONFIGS),
                        default="morocco_australia")
    parser.add_argument("--pitch-candidates", type=int,
                        default=PITCH_CANDIDATES)
    return parser.parse_args()


def configure_from_args(args: argparse.Namespace) -> None:
    global PITCH_CANDIDATES
    PITCH_CANDIDATES = args.pitch_candidates
    apply_case(args.case)


def add_virtual_initial_anchor(scenario) -> None:
    anchor_min = CASE_CONFIGS[CASE_NAME].get("virtual_anchor_min")
    if anchor_min is None:
        return
    anchor_time = T0 + datetime.timedelta(minutes=float(anchor_min))
    lat, lon = kepler2latlong(propagate_orbit(scenario.orbit, anchor_time),
                              anchor_time)
    request = Request(-999, float(lat), float(lon), "virtual_initial_anchor",
                      utility=0.0)
    anchor = Access(
        request,
        anchor_time,
        0.0,
        state={"observed": True, "cloudy": False},
        utility=0.0,
    )
    scenario.cloud_states[anchor.aid] = True
    scenario.schedule_conv = sorted([anchor, *scenario.schedule_conv],
                                    key=lambda a: a.time)
    print(
        f"  virtual initial anchor: {anchor_time.isoformat()} "
        f"sat=({lat:.2f}, {lon:.2f})"
    )


def real_scheduled(schedule: list) -> list:
    return [a for a in schedule if a.utility > 0]


def make_base_config() -> SimConfig:
    return SimConfig(
        t0_iso=T0.isoformat(),
        horizon_h=(T_END - T0).total_seconds() / 3600.0,
        altitude_km=H_KM,
        inclination_deg=INC_DEG,
        n_cities=N_CITIES,
        cloud_prob=CLOUD_PROB,
        cloud_source="iid",
        slew_at_for_s=T_SLEW_FOR_S,
        field_of_regard_deg=FIELD_OF_REGARD_DEG,
        fov_deg=FOV_DEG,
        pitch_candidates=PITCH_CANDIDATES,
        cap_far_edge_at_limb=False,
        variant="break_even",
        seed=42,
        raan_deg=float(np.rad2deg(RAAN)),
        mean_anom_deg=float(np.rad2deg(MEAN_ANOM)),
        tag=CASE_TAG,
    )


def event_footprint(event: dict, orbit, k_matrix: np.ndarray,
                    box_pixels: np.ndarray) -> list[tuple[float, float]]:
    obs_time = datetime.datetime.fromisoformat(event["obs_time_iso"])
    pitch = float(event["best_pitch_deg"])
    orbit_at_obs = propagate_orbit(orbit, obs_time)
    r_obs, _ = kepler2eci(orbit_at_obs)
    ray_points = unproject_from_orbit(
            box_pixels,
            -1,
            k_matrix,
            orbit_at_obs,
            obs_time,
            pitch_angle=pitch,
            roll_angle=0,
        )
    # earth_line_intersection returns the Earth hit at negative line parameter,
    # so pass the opposite of the physical camera ray.
    unproj_dirs = r_obs - ray_points
    intersections = [
        earth_line_intersection(r_obs, direction, horizon_snap=True)[0]
        for direction in unproj_dirs
    ]
    return [
        ecef2latlong(eci2ecef(point, obs_time))
        for point in intersections
    ]


def policy_footprints(results: dict, orbit) -> dict[str, list[dict]]:
    k_matrix = get_intrinsics_from_fov(FOV_DEG, WIDTH, HEIGHT)
    box_pixels = create_box(WIDTH, HEIGHT, points_per_edge=12)
    footprints = {}
    for policy, sim in results.items():
        policy_rows = []
        for event in sim["lookahead_events"]:
            footprint = event_footprint(event, orbit, k_matrix, box_pixels)
            policy_rows.append({
                "event": event,
                "footprint": footprint,
            })
        footprints[policy] = policy_rows
    return footprints


def _track_points(orbit) -> list[tuple[float, float]]:
    return [
        kepler2latlong(
            propagate_orbit(orbit, dt),
            T0 + datetime.timedelta(seconds=float(dt)),
        )
        for dt in np.linspace(0, (T_END - T0).total_seconds(), 400)
    ]


def _common_extent(scenario, footprints: dict[str, list[dict]],
                   track: list[tuple[float, float]]) -> list[float]:
    orbit = scenario.orbit
    s_lat, s_lon = kepler2latlong(propagate_orbit(orbit, T0), T0)
    e_lat, e_lon = kepler2latlong(propagate_orbit(orbit, T_END), T_END)
    all_lats = [s_lat, e_lat, *[lat for lat, _ in track]]
    all_lons = [s_lon, e_lon, *[lon for _, lon in track]]
    for rows in footprints.values():
        for row in rows:
            all_lats.extend(lat for lat, _ in row["footprint"])
            all_lons.extend(lon for _, lon in row["footprint"])
    pad_lat, pad_lon = 6, 8
    return [
        min(all_lons) - pad_lon,
        max(all_lons) + pad_lon,
        min(all_lats) - pad_lat,
        max(all_lats) + pad_lat,
    ]


def _plot_panel(ax, *, policy: str, requests, scenario, track,
                footprints: dict[str, list[dict]], observed_aids: set[int],
                summaries: dict[str, dict], extent: list[float]) -> None:
    orbit = scenario.orbit
    s_lat, s_lon = kepler2latlong(propagate_orbit(orbit, T0), T0)
    e_lat, e_lon = kepler2latlong(propagate_orbit(orbit, T_END), T_END)

    for idx, segment in enumerate(split_orbit_track(track)):
        ax.plot(
            [lon for _, lon in segment],
            [lat for lat, _ in segment],
            color=ORBIT_COLOR,
            lw=1.0,
            transform=ccrs.PlateCarree(),
            label="orbit track" if idx == 0 else None,
            zorder=3,
        )

    ax.plot(
        [r.long for r in requests],
        [r.lat for r in requests],
        ".",
        color=REQUEST_COLOR,
        markersize=1.0,
        alpha=0.45,
        transform=ccrs.PlateCarree(),
        zorder=1,
    )

    observed = [a for a in scenario.accesses if a.aid in observed_aids]
    unobserved = [a for a in scenario.accesses if a.aid not in observed_aids]
    ax.plot(
        [a.long for a in unobserved],
        [a.lat for a in unobserved],
        ".",
        color=UNOBSERVED_ACCESS_COLOR,
        markersize=2.0,
        alpha=0.70,
        transform=ccrs.PlateCarree(),
        label="unobserved accesses",
        zorder=2,
    )
    ax.plot(
        [a.long for a in observed],
        [a.lat for a in observed],
        ".",
        color=OBSERVED_ACCESS_COLOR,
        markersize=3.0,
        alpha=0.90,
        transform=ccrs.PlateCarree(),
        label="observed accesses",
        zorder=4,
    )

    color = POLICY_COLORS[policy]
    label = f"{POLICY_LABELS[policy]} lookahead"
    for idx, row in enumerate(footprints[policy]):
        footprint = row["footprint"]
        ax.plot(
            [lon for _, lon in footprint],
            [lat for lat, _ in footprint],
            color=color,
            lw=1.15,
            alpha=0.95,
            transform=ccrs.PlateCarree(),
            label=label if idx == 0 else None,
            zorder=5,
        )

    ax.plot(
        [s_lon],
        [s_lat],
        "*",
        color="green",
        markersize=8,
        markeredgecolor="black",
        markeredgewidth=0.4,
        transform=ccrs.PlateCarree(),
        label="start",
        zorder=9,
    )
    ax.plot(
        [e_lon],
        [e_lat],
        "*",
        color="red",
        markersize=8,
        markeredgecolor="black",
        markeredgewidth=0.4,
        transform=ccrs.PlateCarree(),
        label="end",
        zorder=9,
    )

    ax.stock_img(alpha=0.15)
    ax.coastlines(linewidth=0.6)
    ax.set_extent(extent, crs=ccrs.PlateCarree())
    gl = ax.gridlines(draw_labels=True, linestyle="--", color="gray", alpha=0.4)
    gl.top_labels = False
    gl.right_labels = False
    gl.xlabel_style = {"size": 7}
    gl.ylabel_style = {"size": 7}

    summary_text = (
        f"{POLICY_LABELS[policy]}\n"
        f"{summaries[policy]['n_lookaheads']} looks, "
        f"{summaries[policy]['dt_clear']:.0f} clear"
    )
    ax.text(
        0.98,
        0.965,
        summary_text,
        transform=ax.transAxes,
        ha="right",
        va="top",
        fontsize=8,
        bbox={"facecolor": "white", "edgecolor": "0.85", "alpha": 0.82, "pad": 2.5},
        zorder=10,
    )
    ax.legend(loc="upper left", frameon=True, ncol=1, fontsize=6.8)


def plot_case_study(requests, scenario, footprints: dict[str, list[dict]],
                    observed_by_policy: dict[str, set[int]],
                    summaries: dict[str, dict]) -> None:
    out_dir = Path(__file__).parent.parent / "figures"
    track = _track_points(scenario.orbit)
    extent = _common_extent(scenario, footprints, track)

    for policy in POLICIES:
        fig = plt.figure(figsize=(4.05, 3.35), dpi=220)
        ax = fig.add_subplot(1, 1, 1, projection=ccrs.PlateCarree())
        _plot_panel(
            ax,
            policy=policy,
            requests=requests,
            scenario=scenario,
            track=track,
            footprints=footprints,
            observed_aids=observed_by_policy[policy],
            summaries=summaries,
            extent=extent,
        )

        out_path = out_dir / f"{OUTPUT_STEMS[policy]}.pdf"
        fig.savefig(out_path, bbox_inches="tight")
        fig.savefig(out_path.with_suffix(".png"), dpi=220, bbox_inches="tight")
        plt.close(fig)
        print(f"Saved {out_path}")


def main() -> None:
    print(f"Loading cities + building scenario for {CASE_NAME}...")
    requests = load_worldcities(n=N_CITIES)
    cfg_base = make_base_config()
    scenario = build_scenario(
        requests=requests,
        raan=RAAN,
        cfg=cfg_base,
        rng=np.random.default_rng(cfg_base.seed),
        t0=T0,
        mean_anom=MEAN_ANOM,
    )
    if scenario is None:
        raise RuntimeError("Case-study scenario had insufficient accesses.")
    add_virtual_initial_anchor(scenario)

    s_lat, s_lon = kepler2latlong(propagate_orbit(scenario.orbit, T0), T0)
    e_lat, e_lon = kepler2latlong(propagate_orbit(scenario.orbit, T_END), T_END)
    print(f"  start sub-satellite: ({s_lat:.2f}, {s_lon:.2f})")
    print(f"  end   sub-satellite: ({e_lat:.2f}, {e_lon:.2f})")
    print(f"  {len(scenario.accesses)} accesses over "
          f"{(T_END - T0).total_seconds() / 60:.0f} min")
    conv_clear = sum(
        a.utility for a in scenario.schedule_conv
        if scenario.cloud_states.get(a.aid, False)
    )
    omni_clear = sum(
        a.utility for a in scenario.schedule_omni
        if scenario.cloud_states.get(a.aid, False)
    )
    schedule_conv_real = real_scheduled(scenario.schedule_conv)
    print(f"  conventional schedule: {len(schedule_conv_real)} tasks, "
          f"clear={conv_clear:.0f}; omniscient clear={omni_clear:.0f}")

    results = {}
    summaries = {}
    observed_by_policy = {}
    for policy in POLICIES:
        cfg = replace(cfg_base, variant=policy)
        sim = _evaluate_variant(scenario, cfg)
        observed_by_policy[policy] = {
            a.aid for a in scenario.accesses
            if a.state.get("observed", False)
        }
        clear = sum(
            a.utility for a in sim["schedule"]
            if scenario.cloud_states.get(a.aid, False)
        )
        results[policy] = sim
        summaries[policy] = {
            "n_lookaheads": int(sim["n_lookaheads"]),
            "dt_clear": float(clear),
            "n_scheduled": len(real_scheduled(sim["schedule"])),
        }
        print(f"  {policy:10s}: {sim['n_lookaheads']:2d} lookaheads, "
              f"clear={clear:.0f}, "
              f"scheduled={len(real_scheduled(sim['schedule']))}")
        for event in sim["lookahead_events"]:
            print(
                f"    {event['obs_time_iso']} "
                f"pitch={event['best_pitch_deg']:.1f} "
                f"score={event['score']:.2f}"
            )

    footprints = policy_footprints(results, scenario.orbit)
    plot_case_study(requests, scenario, footprints, observed_by_policy, summaries)


if __name__ == "__main__":
    configure_from_args(parse_args())
    main()
